[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
log = "^0"
env_logger = "^0"
chrono = "^0"
serde = {version = "^1", features = ["derive"]}
bigdecimal = "^0"
anyhow="^1"