[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
async-std = "^1"
async-channel = "^2"
log = "^0"
toml = "^0"
env_logger = "^0"
once_cell = "^1"
serde = { version = "^1", features = ["derive"] }
chrono = "^0"