[tcp_server]
address = "0.0.0.0"
port = 50100
buffer_size = 262144

[tcp_client]
address = "127.0.0.1"
port = 50100
buffer_size = 1024

[udp_server]
address = "127.0.0.1"
port = 50200
buffer_size = 1024

[udp_client]
address = "127.0.0.1"
port = 50300
buffer_size = 1024

